### ISSUE TITLE
An error occurred while updating user

### ISSUE THREAD

**Issue by zenminimalist** [Swetrix/selfhosting#2]
I'm running into an issue where I get this error.
![CleanShot 2023-09-17 at 15 27 22](https://github.com/Swetrix/selfhosting/assets/7798503/a9d77c4e-4728-4a7b-b517-526504ddbe0c)

Any way to narrow in on what the problem is? Or let me know what you need to see what the issue it. (Not a dev or very well versed techie myself)

I'm running it on Ubunutu 20.04 with OpenLiteSpeed.

**Comment by Blaumaus** [comment]
fixed in the v2.1.2 release
