### ISSUE TITLE
405 Method not allowed when signing in

### ISSUE THREAD

**Issue by tcherokee** [Swetrix/selfhosting#3]
Hello there, 

I am trying to set up Swetrix on GCP compute engine. I followed the selfhosting guide, set up docker on the compute engine and got Swetrix running and everything seems to be working, I can see the Swetrix login page on my browser. The problem starts when I try and log into Swetrix. I keep getting the following error

```
POST https://analytics.example.com 405 method not allowed.
```

I am not exactly sure where the issue is coming from and I am hoping someone can point me in the right direction

**Comment by Blaumaus** [comment]
Hi @tcherokee, taking a look at this issue..

**Comment by tcherokee** [comment]
Hi Blaumaus, Thanks for looking into this for me.

**Comment by tcherokee** [comment]
Hello @Blaumaus, I was just wondering if you made any headway?

**Comment by Blaumaus** [comment]
@tcherokee still testing it, can't reproduce the error. I'll check again and let you know tomorrow

**Comment by Blaumaus** [comment]
So I tested Swetrix Selfhosted again (on a Digital Ocean droplet) - it seems to work as intended, I'm able to log in and add a site.
I also checked the code - we do not send 405 Method Not Allowed anywhere on our API codebase (except for 1 unrelated endpoint), I think it might be an issue with GCP itself

**Comment by tcherokee** [comment]
Quick question, which I am hoping might solve the issue. Do we need to update the following env variable `REACT_APP_AIAPI_URL`. It is not really referenced in the documentation.

So at the moment, I have the site where I want to access swetrix as the `API_URL` (https://analytics.example.com) and `REACT_APP_AIAPI_URL` is currently the default value of `https://aiapi.swetrix.com/`. 

Just wanted to make sure that is accurate.

**Comment by Blaumaus** [comment]
Hi, sorry for a delayed reply. I don't think the AI API is related to the issue, as it's used as a traffic forecasting tool within the analytics dashboard only

**Comment by Blaumaus** [comment]
Did you manage to find a solution for that bug?

**Comment by WebKenth** [comment]
You need to set the API url correctly:

`swetrix` needs to be able to communicate with `swetrix-api`

`swetrix` runs in this example on localhost:8081
`swetrix-api` runs in this example on localhost:8080
<img width="522" alt="image" src="https://github.com/Swetrix/selfhosting/assets/13419123/c6daf859-8660-4b41-84a8-8848e46c912b">

**Comment by Blaumaus** [comment]
I'm taking a look into this, but just to clarify: is `http://analytics.example.com` the domain of your Swetrix frontend or backend instance?

It might be sending these requests to the React server intead of the API, as according to the config frontend it exposed on port 80, while the API is on port 8080. Have you tried replacing the `API_URL` with `http://analytics.example.com:8080`?

**Comment by tcherokee** [comment]
http://analytics.example.com is the url for the swetrix frontend. Do I need to set up a backend for swetrix and if so where do i define the url for the backend?

I will try updating the `API_URL` to `http://analytics.example.com:8080 and get back to you. I am also open to giving you access to the server I am hosting swetrix on if it will help with the debugging.

**Comment by tcherokee** [comment]
Ok, if I update the `API_URL` to `http://analytics.example.com:8080`, I do not get the 405 error anymore, but when I try and login,  I get the following error in the console tab `POST http://analytics.example.com:8080/v1/auth/login net:: ERR_CONNECTION_TIMED_OUT`

**Comment by Blaumaus** [comment]
> http://analytics.example.com is the url for the swetrix frontend. Do I need to set up a backend for swetrix and if so where do i define the url for the backend?
> 
> I will try updating the `API_URL` to `http://analytics.example.com:8080 and get back to you. I am also open to giving you access to the server I am hosting swetrix on if it will help with the debugging.

API_URL is a URL of the server which will be used on the frontend.

API and Frontend run on the same docker-compose file, but on different ports.
By default API is on port 8080, frontend is on port 80.

You can set up Nginx or just expose these ports directly for it to work (this is what I did on my test Digital Ocean set up).

And you open http://analytics.example.com:8080 directly in your browser and see it it returns something? By default it should return a JSON like `{"message":"Cannot GET /","error":"Not Found","statusCode":404}` which means that API is accessible on that port.

**Comment by Blaumaus** [comment]
I can take a look at this, you can contact me using email at https://swetrix.com/contact

Also one more question: if you run `curl localhost:8080` on your server, do you get any response at all?

**Comment by tcherokee** [comment]
Sent an email,

The command `curl localhost:80080` returns a 404. This is the full error

`{"statusCode":404,"message":"Cannot GET /","error":"Not Found"}`

**Comment by Blaumaus** [comment]
> Sent an email,
> 
> The command `curl localhost:80080` returns a 404. This is the full error
> 
> `{"statusCode":404,"message":"Cannot GET /","error":"Not Found"}`

It means that the API is running well on that port. If you tried adding this port to the API_URL and it returned an error, are you sure this port is exposed to internet?
Do you have a reverse proxy installed like nginx, or a ufw or anything like that that might interfere?

**Comment by tcherokee** [comment]
Ok, so to get it to work I had to do a couple of things.

1. Set up nginx and use the nginx config from the repo.
2. Update my docker-compose and included to port the nginx will be listening to API request on. In my case it was 8081. so my API_URL became `https://analytics.example.com:8081/
3. Opened the 8081 port on the server. otherwise you will get a connection timed out error in the network tab.

many thanks to @Blaumaus for all his help in sorting this out.
