### ISSUE TITLE
Clickhouse default configuration

### ISSUE THREAD

**Issue by KaelWD** [Swetrix/selfhosting#9]
The default log level is trace which uses loads of disk space for no reason: https://theorangeone.net/posts/calming-down-clickhouse/

It also expects at least 16GB of ram which could cause problems on smaller servers without some tweaks: https://clickhouse.com/docs/en/operations/tips#using-less-than-16gb-of-ram

**Comment by Blaumaus** [comment]
We disable Clickhouse query logs for selfhosted [here](https://github.com/Swetrix/swetrix/blob/main/backend/apps/selfhosted/src/common/integrations/clickhouse.ts#L72), and set up proper error logging [here](https://github.com/Swetrix/swetrix/blob/main/backend/apps/selfhosted/src/common/integrations/clickhouse.ts#L79).

Does Clickhouse use lots of disk space for you?

But I agree on that point, we should supply proper Clickhouse config to set up things like that.

**Comment by KaelWD** [comment]
I didn't actually check the query log before clearing it so that might have been ok already, `/var/log/clickhouse/clickhouse-server.log` was 800MB of verbose level logs though so something is definitely not configured correctly.

**Comment by Blaumaus** [comment]
Thank you for adding this. I'll play around with configs as well to see what works best for the next release.
Please let me know how did Clickhouse end up performing for you if you test it on that 200k traffic site

**Comment by KaelWD** [comment]
Got 150k over the weekend and the dashboard is still fast, clickhouse memory hasn't gone over 500MB. I might need to increase the limits a bit once there's a few months of data but I think this is probably totally fine as a starting point for smaller sites.

**Comment by Blaumaus** [comment]
https://github.com/Swetrix/selfhosting/pull/10 I've opened a PR with some configs. I've put your config to reduce RAM usage there as well.

It will be merged into the next self-hosted release, let me know if you have any further suggestions to these configuration files.

Also thank you very much for contributing to the project, it helps a lot!
